version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./docker/checkout.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  php:
    build: .
    volumes:
      - .:/var/www/html
      - ./docker/php.custom.ini:/usr/local/etc/php/conf.d/php.custom.ini
